language: node_js
node_js:
  - '11'
  - '10'
  - '8'
sudo: false
cache: npm

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script:
        - npm run test:all
